# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from seleniumbase import BaseCase
from user_operation import UserOperation
BaseCase.main(__name__, __file__)

# from test_login import TestLogin

class TestLogout(BaseCase):
  # def setup_method(self, method):
  #   self.driver = webdriver.Chrome()
  #   self.vars = {}
  
  # def teardown_method(self, method):
  #   self.driver.quit()
  
  def test_logout(self):
    op = UserOperation(self)
    op.login()
    self.wait_for_element(".anticon-close > svg",By.CSS_SELECTOR,2)
    self.driver.find_element(By.CSS_SELECTOR, ".anticon-close > svg").click()
    # self.driver.get("http://localhost:5173/")
    # self.driver.set_window_size(1552, 832)
    self.wait_for_element(".vben-header-user-dropdown.ant-dropdown-trigger",By.CSS_SELECTOR,2000)
    # self.driver.find_element(By.CSS_SELECTOR, ".vben-header-user-dropdown.ant-dropdown-trigger").click()
    self.hover_over_element(".vben-header-user-dropdown.ant-dropdown-trigger",By.CSS_SELECTOR,3000)
    self.sleep(1)
    # WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".ant-dropdown-menu")))
    self.wait_for_element(".ant-dropdown-menu",By.CSS_SELECTOR,3000)
    self.assert_element(".ant-dropdown-menu",By.CSS_SELECTOR)
    self.driver.find_element(By.XPATH, "//li[contains(.,\'退出系统\')]").click()
    self.sleep(1)
    # self.driver.find_element(By.XPATH, "//html[@id='htmlRoot']/body/div[6]/div/div/ul/li[5]").click()
    WebDriverWait(self.driver, 1).until(expected_conditions.element_to_be_clickable((By.XPATH, "//button[contains(.,\'确 定\')]")))
    self.driver.find_element(By.XPATH, "//button[contains(.,\'确 定\')]").click()
    self.sleep(1)
  