# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class UserOperation(BaseCase):
  def __init__(self,test_instance,*args, **kwargs):
    super().__init__(*args, **kwargs)
    self.test_instance = test_instance
    # self.driver = webdriver.Chrome()
  
  # def teardown_method(self, method):
  #   self.driver.quit()
  
  def login(self,account = 'vben',password = '123456'):
    # self.driver = webdriver.Chrome()
    self.test_instance.driver.get("http://localhost:5173/")
    self.test_instance.driver.set_window_size(1536, 816)
    self.test_instance.wait_for_element("form_item_account",By.ID,2)
    # self.driver.find_element(By.ID, "form_item_account").click()
    # self.driver.find_element(By.ID, "form_item_account").send_keys(" ")
    # self.driver.find_element(By.ID, "form_item_account").send_keys("vben")
    self.test_instance.type("#form_item_account",account)
    self.test_instance.type("#form_item_password",password)
    # self.driver.find_element(By.ID, "form_item_password").click()
    # self.driver.find_element(By.ID, "form_item_password").send_keys(" ")
    # self.driver.find_element(By.ID, "form_item_password").send_keys("123456")
    self.test_instance.driver.find_element(By.CSS_SELECTOR, ".ant-btn-primary > span").click()


